AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create infrastructure for the rod licensing digital services (local development only)
Resources:
  TransactionStaging:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransactionStaging
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      TimeToLiveSpecification:
        AttributeName: 'expires'
        Enabled: true

  TransactionStagingHistory:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TransactionStagingHistory
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      TimeToLiveSpecification:
        AttributeName: 'expires'
        Enabled: true

  PaymentJournals:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PaymentJournals
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'paymentStatus'
          AttributeType: 'S'
        - AttributeName: 'paymentTimestamp'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      TimeToLiveSpecification:
        AttributeName: 'expires'
        Enabled: true
      GlobalSecondaryIndexes:
        - IndexName: 'PaymentJournalsByStatusAndTimestamp'
          KeySchema:
            - AttributeName: 'paymentStatus'
              KeyType: 'HASH'
            - AttributeName: 'paymentTimestamp'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'
          # Shouldn't need to specify this when using BillingMode: 'PAY_PER_REQUEST' but localstack requires it....
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  PoclFileStaging:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PoclFileStaging
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'filename'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'filename'
          KeyType: 'HASH'
      TimeToLiveSpecification:
        AttributeName: 'expires'
        Enabled: true

  PoclRecordStaging:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PoclRecordStaging
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: 'filename'
          AttributeType: 'S'
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'filename'
          KeyType: 'HASH'
        - AttributeName: 'id'
          KeyType: 'RANGE'
      TimeToLiveSpecification:
        AttributeName: 'expires'
        Enabled: true

  PoclAuditBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pocl-audit

  FulfilmentAuditBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fulfilment-audit
# At the time of writing (Mar 2020) there are problems using cloudformation templates to initialise SQS queues (FIFO support)
# SalesQueue:
#    Type: AWS::SQS::Queue
#    Properties:
#      QueueName: SalesQueue.fifo
#      FifoQueue: True
#      ContentBasedDeduplication: True
#      DelaySeconds: 10
#      VisibilityTimeout: 30
#      MessageRetentionPeriod: 1209600 # 14 days
#      RedrivePolicy:
#        deadLetterTargetArn:
#          Fn::GetAtt:
#            - SalesDeadLetterQueue
#            - Arn
#        maxReceiveCount: 5
#  SalesDeadLetterQueue:
#    Type: AWS::SQS::Queue
#    Properties:
#      QueueName: SalesDeadLetterQueue.fifo
#      FifoQueue: True
#      DelaySeconds: 30
#      VisibilityTimeout: 30
#      MessageRetentionPeriod: 1209600 # 14 days
