apps:
  - script: ./src/sales-api-service.js
    interpreter_args: '--unhandled-rejections=strict'
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000
