version: '3.7'
services:
  #######################################################
  # Localstack services for development
  #
  # - DynamoDB (http port 4569)
  # - S3 (http port 4572)...
  # - SQS (http port 4576)
  # - CloudFormation (http port 4581)
  #######################################################
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '${PORT_WEB_UI-4080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=s3,dynamodb,cloudformation
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/localstack:/tmp/localstack
      - ./resources/infrastructure/localstack/localstack-init.sh:/docker-entrypoint-initaws.d/init.sh
      - ./resources/infrastructure/localstack/localstack-cfn.yml:/docker-entrypoint-initaws.d/localstack-cfn.yml
    deploy:
      restart_policy:
        condition: on-failure

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8002:8001'
    environment:
      - DYNAMO_ENDPOINT=http://host.docker.internal:4569
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Redis
  #######################################################
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data
    deploy:
      restart_policy:
        condition: on-failure

  redis_insight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - ./volumes/redisinsight:/db
    deploy:
      restart_policy:
        condition: on-failure

  redis_commander:
    image: rediscommander/redis-commander
    ports:
      - '8003:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Elasticmq (SQS provider)
  #######################################################
  elasticmq:
    image: s12v/elasticmq
    ports:
      - '9324:9324'
    volumes:
      - type: bind
        read_only: true
        source: resources/infrastructure/elasticmq/elasticmq.conf
        target: /etc/elasticmq/elasticmq.conf
    deploy:
      restart_policy:
        condition: on-failure

  #######################################################
  # Test SFTP server
  #######################################################
  test_sftp:
    image: atmoz/sftp:alpine
    ports:
      - '2222:22'
    volumes:
      - ./resources/infrastructure/sftp/sshd_config:/etc/ssh/sshd_config
      - ./resources/infrastructure/sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./resources/infrastructure/sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./resources/infrastructure/sftp/ssh_host_rsa_key.pub:/home/test_sftp_user/.ssh/keys/id_rsa.pub:ro
      - ./volumes/sftp:/home/test_sftp_user/share
    command: test_sftp_user::1001
    deploy:
      restart_policy:
        condition: on-failure
