version: '3.7'
#######################################################
# Common project docker build options
#######################################################
x-common-build-options: &common-build-options
  context: ${BUILD_CONTEXT:-../}

services:
  ##############################################################################################################
  # Rod licensing services base image
  #
  # This is not designed to be deployed but to serve as the base image for rod-licensing services.
  ##############################################################################################################
  rod-licensing-base:
    image: rod-licensing/base
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.base

  ##############################################################################################################
  # rod-licensing services builder image
  #
  # This is not designed to be deployed but to serve as the base image for building rod-licensing services.
  # Provides additional libraries for the build process not required at runtime.
  ##############################################################################################################
  rod-licensing-builder:
    image: rod-licensing/builder
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.build

  ##############################################################################################################
  # rod-licensing webapp
  ##############################################################################################################
  webapp:
    image: rod-licensing/webapp:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/gafl-webapp-service/${PROJECT_DOCKERFILE:-Dockerfile}

  ##############################################################################################################
  # rod-licensing sales_api
  ##############################################################################################################
  sales_api:
    image: rod-licensing/sales_api:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/sales-api-service/${PROJECT_DOCKERFILE:-Dockerfile}

  ##############################################################################################################
  # rod-licensing sqs_receiver
  ##############################################################################################################
  sqs_receiver:
    image: rod-licensing/sqs_receiver:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/sqs-receiver-service/${PROJECT_DOCKERFILE:-Dockerfile}
