version: '3.7'
#######################################################
# Common project docker build options
#######################################################
x-common-build-options: &common-build-options
  context: ${BUILD_CONTEXT:-../}

services:
  ##############################################################################################################
  # Rod licencing services base image
  #
  # This is not designed to be deployed but to serve as the base image for rod-licencing services.
  ##############################################################################################################
  rod-licencing-base:
    image: rod-licencing/base:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.base

  ##############################################################################################################
  # rod-licencing services builder image
  #
  # This is not designed to be deployed but to serve as the base image for building rod-licencing services.
  # Provides additional libraries for the build process not required at runtime.
  ##############################################################################################################
  rod-licencing-builder:
    image: rod-licencing/builder:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: Dockerfile.build

  ##############################################################################################################
  # rod-licencing webapp
  ##############################################################################################################
  webapp:
    image: rod-licencing/webapp:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/gafl-webapp-service/${PROJECT_DOCKERFILE:-Dockerfile}

  ##############################################################################################################
  # rod-licencing sales_api
  ##############################################################################################################
  sales_api:
    image: rod-licencing/sales_api:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/sales-api-service/${PROJECT_DOCKERFILE:-Dockerfile}

  ##############################################################################################################
  # rod-licencing sqs_receiver
  ##############################################################################################################
  sqs_receiver:
    image: rod-licencing/sqs_receiver:${TAG:-latest}
    build:
      <<: *common-build-options
      dockerfile: packages/sqs-receiver-service/${PROJECT_DOCKERFILE:-Dockerfile}
