version: '3.7'
services:
  ##############################################################################################################
  # rod-licensing webapp
  ##############################################################################################################
  webapp:
    image: rod-licensing/webapp:${TAG:-latest}
    ports:
      - 3000:3000
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod-licensing sales_api
  ##############################################################################################################
  sales_api:
    image: rod-licensing/sales_api:${TAG:-latest}
    ports:
      - 4000:4000
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  ##############################################################################################################
  # rod-licensing sqs_receiver
  ##############################################################################################################
  sqs_receiver:
    image: rod-licensing/sqs_receiver:${TAG:-latest}
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
