apps:
  - script: ./src/sqs-receiver-service.js
    name: 'Sales Queue'
    env:
      RECEIVER_PREFIX: SALES_QUEUE
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000

  - script: ./src/sqs-receiver-service.js
    name: 'Sales dead letter queue'
    env:
      RECEIVER_PREFIX: SALES_DLQ
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000
