apps:
  - script: ./src/sqs-receiver-service.js
    name: 'Transactions Queue'
    env:
      RECEIVER_PREFIX: TRANSACTIONS_QUEUE
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000

  - script: ./src/sqs-receiver-service.js
    name: 'Transactions DLQ'
    env:
      RECEIVER_PREFIX: TRANSACTIONS_DLQ
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000
