apps:
  - script: ./src/sqs-receiver-service.js
    interpreter_args: '--unhandled-rejections=strict'
    name: 'Transactions Queue'
    env:
      RECEIVER_PREFIX: TRANSACTION_QUEUE
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000

  - script: ./src/sqs-receiver-service.js
    interpreter_args: '--unhandled-rejections=strict'
    name: 'Transactions DLQ'
    env:
      RECEIVER_PREFIX: TRANSACTION_DLQ
    exec_mode: cluster
    instances: 1
    autorestart: true
    max_restarts: 5
    restart_delay: 1000
