apps:
  - script: ./src/sqs-receiver-service.js
    interpreter_args: '--unhandled-rejections=strict'
    name: 'Transactions Queue'
    env:
      RECEIVER_PREFIX: TRANSACTION_QUEUE
    exec_mode: fork
    kill_timeout: 180000
    autorestart: true
    max_restarts: 3
    restart_delay: 5000

  - script: ./src/sqs-receiver-service.js
    interpreter_args: '--unhandled-rejections=strict'
    name: 'Transactions DLQ'
    env:
      RECEIVER_PREFIX: TRANSACTION_DLQ
    exec_mode: fork
    kill_timeout: 180000
    autorestart: true
    max_restarts: 3
    restart_delay: 5000
