name: build

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - IWTF-1971-version-script-single-quote

jobs:
  new-version:
    name: new-version
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Run versioning script
        run: COMMIT_MESSAGE='${{ toJSON(github.event.head_commit.message)}}' BRANCH='${{ steps.extract_branch.outputs.branch }}' . ./scripts/github/deploy.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
