name: build

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  tests:
    name: tests
    runs-on: ubuntu-18.04
    env:
      TZ: Europe/London
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run arbitrarty script
        run: COMMIT='${{github.event.head_commit.message}}' . ./scripts/github/deploy.sh
  sonar-scanner:
    name: sonar-scanner
    runs-on: ubuntu-18.04
    needs: tests
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 